name: 'InstallResourceKit'
description: 'Install the APIM DevOps Resource Kit'
inputs:
  creds:  
    description: 'Azure Credentials, typically stored in a secret'
    required: true
  releaseVersion:  
    description: 'The APIM DevOps Resource Kit version'
    required: true
    default: '0.7'
runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.creds }}
    - name: Download and extract APIM Devops Resource Kit Release
      shell: bash
      run: |
        wget "https://github.com/Azure/azure-api-management-devops-resource-kit/archive/refs/tags/v${{inputs.releaseVersion}}.tar.gz" && tar xvzf "v${{inputs.releaseVersion}}.tar.gz" && rm "v${{inputs.releaseVersion}}.tar.gz"
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
        include-prerelease: true
    - name: Build and Install Resource Kit as a global tool
      shell: bash
      run: |
        dotnet restore
        dotnet build ./apimtemplate.csproj --no-restore
        dotnet pack -c Release
        dotnet tool install -g --add-source ./bin/Release apimtemplate
      working-directory: "./azure-api-management-devops-resource-kit-${{inputs.releaseVersion}}/src/APIM_ARMTemplate/apimtemplate"


